travis:
  secure:
    BINSTAR_TOKEN: e6qq5bdAmTpU5A7kIcTr0qgAegFDEc9tE6BoOPn+aZ5KaAQsMN/wXgmxvI+BHS2Vfmw0q+IpjDdF72+nhIdFBKkdjR8qPbarF8Yf3r0CWnnXu6iMWpMycG8cdj3wbvP0NELy2L1ZD+Vl95/xTlxC4yPlboZRLvY2mlC9FErSC3YOC5WKYqcXjVJo3Vyp7WmdC1mgc324TU3uqyz0W/ti4N7lTbH4PccP2gDIfj7ahkUHC8fRdhzbeadc+ix6kbnOY3iAJmzgloYCrFcPCBxPaaWTwNCRgumIbFQ5Q8j9+PH+pTLo8Z/JABqngGNnmhsxk2imVECX2sGyhZsUG6IMjAEBeSqAlolUwm8o4Vgrt1sRltL8qVR8Yq7r7Vxc3iMlF3xJf3B1paS9EesfIyHpayO2mwWloRbVlXPT9hq8KhCtNZBL9+ObXQUq5x+j0zQ50TMcyqHb6V8XHK8kRghnIUMf5tTZug4dKZDhr0wTsYq/VmMgsdHsnYp8CaHSynqMnVSmavh7gUK0xVWIVRd7Z6ol7Lnb4UAnxihQR8afcFwLYTckCUOna/T/27SmEx4vtEz0Dg1pkgQ+nWISRVyr+3L/w5QPkM/5hTgpRzH33PAvWaddhxRBb61PrWik/jJwbiXpTQrk4ivgU90h8AgEGTzU7BtRu2roVvtIsomwisM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
